// Função para traduzir as raças
function translateBreeds(breed) {
    const breeds = {
        "affenpinscher": "pinscher affen", 
        "african": "africano", 
        "airedale": "airedale terrier",
        "appenzeller": "boiadeiro de appenzell", 
        "australian-kelpie": "kelpie australiano", 
        "australian-shepherd": "pastor australiano",
        "bakharwal-indian": "bakharwal indiano",
        "bouvier": "boiadeiro da flandres",
        "brabancon": "brabançon", 
        "briard": "pastor de brie",
        "buhund-norwegian": "buhund norueguês", 
        "bulldog-boston": "buldogue boston", 
        "bulldog-english": "buldogue inglês", 
        "bulldog-french": "buldogue francês", 
        "bullterrier-staffordshire": "staffordshire bull terrier",
        "cattledog-australian": "boiadeiro australiano",
        "chippiparai-indian": "chippiparai indiano", 
        "chow": "chow-chow",
        "collie-border": "border collie",
        "corgi-cardigan": "welsh corgi cardigan", 
        "corgi": "welsh corgi", 
        "cotondetulear": "coton de tulear", 
        "dachshund": "salsicha", 
        "dalmatian": "dálmata",
        "danish-swedish-farmdog": "fazendeiro dinamarquês", 
        "deerhound-scottish": "lebrel escocês", 
        "dhole": "cão selvagem asiático", 
        "elkhound-norwegian": "elkhound norueguês",
        "entlebucher": "boiadeiro de entlebuch", 
        "eskimo": "esquimó", 
        "finnish-lapphund": "cão finlandês", 
        "frise-bichon": "bichon frisé", 
        "gaddi-indian": "gaddi kutta", 
        "germanshepherd": "pastor alemão",
        "greyhound-indian": "galgo indiano", 
        "greyhound-italian": "galgo italiano", 
        "greyhound": "galgo", 
        "groenendael": "pastor belga", 
        "havanese": "bichon havanês", 
        "hound-afghan": "galgo afegão",
        "hound-basset": "basset hound", 
        "hound-blood": "cão de santo humberto", 
        "hound-english": "cão inglês", 
        "hound-ibizan": "podengo ibicenco", 
        "hound-plott": "plott hound", 
        "hound-walker": "walker hound",
        "lhasa": "lhasa apso", 
        "malamute": "malamute do alasca", 
        "malinois": "pastor belga", 
        "maltese": "maltês", 
        "mastiff-bull": "bulmastife", 
        "mastiff-english": "mastim inglês", 
        "mastiff-indian": "mastim indiano",
        "mastiff-tibetan": "mastim tibetano", 
        "mexicanhairless": "pelado mexicano", 
        "mix": "vira-lata", 
        "mountain-bernese": "boiadeiro de berna", 
        "mountain-swiss": "boiadeiro suíço", 
        "mudhol-indian": "mudhol indiano",
        "newfoundland": "cão terra nova",
        "ovcharka-caucasian": "pastor caucasiano",
        "pariah-indian": "pária indiano", 
        "pekinese": "pequinês",
        "pembroke": "corgi pembroke", 
        "pinscher-miniature": "pinscher miniatura",
        "pointer-german": "pointer alemão", 
        "pointer-germanlonghair": "pointer alemão",
        "pomeranian": "zwergspitz", 
        "poodle-medium": "poodle médio", 
        "poodle-miniature": "poodle miniatura", 
        "poodle-standard": "poodle",
        "pyrenees": "pirineus", 
        "rajapalayam-indian": "rajapalayam indiano",
        "retriever-chesapeake": "retriever de chesapeake", 
        "retriever-curly": "retriever cacheado",
        "retriever-flatcoated": "retriever liso", 
        "retriever-golden": "golden retriever", 
        "ridgeback-rhodesian": "rhodesian ridgeback",
        "samoyed": "samoieda",
        "schnauzer-giant": "schnauzer gigante", 
        "schnauzer-miniature": "schnauzer miniatura",
        "segugio-italian": "segugio italiano",
        "setter-english": "setter inglês", 
        "setter-gordon": "setter gordon", 
        "setter-irish": "setter irlandês", 
        "sharpei": "shar pei", 
        "sheepdog-english": "sheepdog inglês", 
        "sheepdog-indian": "sheepdog indiano",
        "sheepdog-shetland": "shetland sheepdog", 
        "spaniel-blenheim": "king charles spaniel", 
        "spaniel-brittany": "spaniel bretão", 
        "spaniel-cocker": "cocker spaniel",
        "spaniel-irish": "irish spaniel", 
        "spaniel-japanese": "spaniel japonês", 
        "spaniel-sussex": "sussex spaniel",
        "spitz-indian": "spitz indiano",
        "spitz-japanese": "spitz japonês", 
        "springer-english": "springer spaniel", 
        "stbernard": "São Bernardo", 
        "terrier-american": "terrier americano", 
        "terrier-australian": "terrier australiano",
        "terrier-bedlington": "bedlington terrier", 
        "terrier-border": "border terrier", 
        "terrier-boston": "boston terrier", 
        "terrier-cairn": "cairn terrier", 
        "terrier-dandie": "dandie terrier",
        "terrier-fox": "fox terrier", 
        "terrier-irish": "irish terrier", 
        "terrier-kerryblue": "kerry blue terrier", 
        "terrier-lakeland": "lakeland terrier", 
        "terrier-norfolk": "norfolk terrier",
        "terrier-norwich": "norwich terrier", 
        "terrier-patterdale": "patterdale terrier", 
        "terrier-russell": "russell terrier", 
        "terrier-scottish": "scottish terrier", 
        "terrier-sealyham": "sealyham terrier",
        "terrier-silky": "silky terrier", 
        "terrier-tibetan": "terrier tibetano",
        "terrier-welsh": "welsh terrier", 
        "terrier-westhighland": "west highland terrier",
        "terrier-wheaten": "wheaten terrier", 
        "terrier-yorkshire": "yorkshire terrier",
        "vizsla": "vizsla húngaro", 
        "waterdog-spanish": "cão d'água espanhol", 
        "wolfhound-irish": "irish wolfhound"
    };

    if (breeds[breed]) {
        return breeds[breed].toUpperCase()
    } else {
        return breed.replace('-', ' ').toUpperCase()
    }
}